language: csharp
dist: trusty
mono: 5.10.1
solution: Recurly.sln
install:
  - nuget restore Recurly.sln
  - nuget install xunit.runner.console -Version 2.4.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Recurly.sln
  - ./scripts/test Release
